### ISSUE TITLE
getChannelId returns null on the first run without creating airshipconfig on android

### ISSUE THREAD

**Issue by dkulakov** [urbanairship/react-native-airship#508] opened 2023-05-06 16:05 UTC
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

`"urbanairship-react-native": "14.6.0"`

### What are the versions of any relevant development tools you are using?

`"react-native": "0.70.6"`
`"@react-native-firebase/messaging": "17.1.0"`
`"react-native-push-notification": "8.1.1"`

# Report

### What unexpected behavior are you seeing?

on the first run UrbanAirship.getChannelId() returns null for some reason if I don't create `airshipconfig.properties` for Android

### What is the expected behavior?

UrbanAirship.getChannelId() should return channelId on the first run on android without creating airshipconfig files

```
UrbanAirship.takeOff({
  default: {
    appSecret: Config.AIRSHIP_APP_SECRET,
    appKey: Config.AIRSHIP_APP_KEY,
  },
  site: 'us',
  urlAllowList: ['*'],
  inProduction: false,
})
```

### What are the steps to reproduce the unexpected behavior?

Do not create the `airshipconfig.properties` file for android and try to run an application.

**Comment by dkulakov** [comment] 2023-05-10 19:36
Hi @rlepinski , I need your help :)
Please check my stack trace at your convenience

**Comment by rlepinski** [comment] 2023-05-12 18:44
@dkulakov That is just logs, if you can reproduce the crash you should get a full stack trace starting with that checkNotNull line that you posted in the screenshot. It should show up as a fatal if you get the app to actually crash. If not, I think in the metro window will have the full stack if you reproduce while debugging.

**Comment by dkulakov** [comment] 2023-05-12 18:59
@rlepinski is that what you are asking for?

```
E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException
        at android.os.Parcel.createException(Parcel.java:1972)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.os.Parcel.readException(Parcel.java:1884)
        at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:1888)
        at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:577)
        at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:565)
        at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.checkOrCreateChannel(RNPushNotificationHelper.java:919)
        at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.createChannel(RNPushNotificationHelper.java:944)
        at com.dieam.reactnativepushnotification.modules.RNPushNotification.createChannel(RNPushNotification.java:316)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.jni.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:111)
        at com.android.server.notification.RankingHelper.createNotificationChannel(RankingHelper.java:631)
        at com.android.server.notification.NotificationManagerService$12.createNotificationChannelsImpl(NotificationManagerService.java:2600)
        at com.android.server.notification.NotificationManagerService$12.createNotificationChannels(NotificationManagerService.java:2615)
        at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:292)
```

**Comment by dkulakov** [comment] 2023-05-12 21:51
@rlepinski I found the root cause of the crash:
I use `'react-native-push-notification' (PushNotification.createChannel(channelId))`, but on the first run `UrbanAirship.getChannelId()` returns `null` for some reason.

**Comment by rlepinski** [comment] 2023-05-12 22:09
@dkulakov The channel ID is created through a network request, so its not available right away.  You can listen for creation using the `registration` event:

```
 UrbanAirship.addListener("registration", (event) => {
        console.log('registration:', JSON.stringify(event))
        this.state.channelId = event.channelId
})

**Comment by dkulakov** [comment] 2023-05-12 22:12
@rlepinski looks like it's an old [issue](https://github.com/urbanairship/react-native-airship/issues/460)
if I use airshipconfig.properties it works like a charm, but if I use `UrbanAirship.takeOff()` I face this issue

**Comment by rlepinski** [comment] 2023-05-12 22:36
The first issue was an integration issue, the second issue did not have any responses and was probably due to delayed channel registration. 

Could you provide the airshipconfig.properties file without your secrets?

**Comment by dkulakov** [comment] 2023-05-12 22:37
```
UrbanAirship.takeOff({
  default: {
    appSecret: Config.AIRSHIP_APP_SECRET,
    appKey: Config.AIRSHIP_APP_KEY,
  },
  site: 'us',
  urlAllowList: ['*'],
  inProduction: false,
})
```

```
developmentAppKey = TODO
developmentAppSecret = TODO

productionAppKey = TODO
productionAppSecret = TODO

inProduction = false
```

**Comment by rlepinski** [comment] 2023-05-12 22:38
Are you getting a registration event when calling takeOff in code? 
```
 UrbanAirship.addListener("registration", (event) => {
        console.log('registration:', JSON.stringify(event))
})
```

**Comment by dkulakov** [comment] 2023-05-12 22:39
yes, I'm getting a registration event when calling takeOff in code

**Comment by rlepinski** [comment] 2023-05-12 22:41
Everything seems like its working then. The channel ID is created through an REST api call. When takeOff is being called through airship config its probably just happening before you try to access it since Airship will be initialized very early in the lifecycle compared to calling it in JS. However, you should handle accessing the channel ID through the registration event in cases where it wont be immediately available.

**Comment by dkulakov** [comment] 2023-05-12 22:44
yes, that makes sense. Thank you for your help!

**Closed** 2023-05-12 22:45 UTC
